/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: sirsaugsage (https://sketchfab.com/sirsausage)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/fantasy-game-inn-192bf30a7e28425ab385aef19769d4b0
title: Fantasy Game Inn
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function InnHouseModel(props) {
  const { nodes, materials } = useGLTF('/fantasy_game_inn.glb')
  console.log(nodes)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[338.07, 62.04, 21.64]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.3, 0.46, -1.38]}>
              <mesh geometry={nodes.TheInn_bakeInn_0.geometry} material={materials.bakeInn} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/fantasy_game_inn.glb')
