/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: BojanBabic (https://sketchfab.com/bokadigimon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/poa-pratensis-b94b529fdf8c452f93dbf8302b579caf
title: Poa Pratensis
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function GrassModel(props) {
  const { nodes, materials } = useGLTF('/Grass.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.10}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh 
            geometry={nodes.VP_Poa_pratensis_V2_001_VP_Poa_Prat_Leaf_01_0.geometry} 
            material={materials.VP_Poa_Prat_Leaf_01} 
            />
            <mesh 
            geometry={nodes.VP_Poa_pratensis_V2_001_VP_Poa_Prat_Leaf_02_0.geometry} 
            material={materials.VP_Poa_Prat_Leaf_02} 
            />
            <mesh 
            geometry={nodes.VP_Poa_pratensis_V2_001_VP_Poa_Prat_Leaf_04_0.geometry} 
            material={materials.VP_Poa_Prat_Leaf_04} 
            />
            <mesh 
            geometry={nodes.VP_Poa_pratensis_V2_001_VP_Poa_Prat_Leaf_03_0.geometry} 
            material={materials.VP_Poa_Prat_Leaf_03} 
            />
            <mesh 
            geometry={nodes.VP_Poa_pratensis_V2_001_VP_Poa_Prat_Seed_01_0.geometry} 
            material={materials.VP_Poa_Prat_Seed_01} 
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Grass.glb')
