/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: bocharova (https://sketchfab.com/apsnu)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/swamp-location-7ede00c0dfe14574bd8f06ee36020609
title: swamp location
*/

import React, { Suspense, useEffect, useMemo, useRef } from 'react'
import { Merged, Plane, Polyhedron, RoundedBox, useGLTF } from '@react-three/drei';
import { Physics, RigidBody, Debug, CuboidCollider, WorldApi, MeshCollider, useRapier } from "@react-three/rapier";
import * as THREE from 'three'

export function SwampModel(props) {

  const { nodes, materials } = useGLTF('/swamp_location.glb')
  // const model = useGLTF('/swamp_location.glb');

  function loadTexture(path) {
    const texture = new THREE.TextureLoader().load(path);
    texture.wrapS = texture.wrapT = THREE.RepeatWrapping;
    texture.repeat.x = 10;
    texture.repeat.y = 10;
    return texture;
}

  return (
  

      // <GroundFloor/>
      <group {...props} dispose={null}>
        <group> 
            <RigidBody colliders="trimesh" type="fixed" rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Object_2.geometry} material={materials.map_1blinn6SG} name="obj1"/>
              <mesh geometry={nodes.Object_3.geometry} material={materials.map_1lambert4SG} name="obj2"/>
              <mesh geometry={nodes.Object_4.geometry} material={materials.map_1object} name="obj3"/>
              <mesh geometry={nodes.Object_5.geometry} material={materials.map_1object} name="obj4" />
              <mesh geometry={nodes.Object_6.geometry} material={materials.map_1lambert5SG} name="obj5" /> 
            </RigidBody>
        </group>
      </group>
   
  )
}

useGLTF.preload('/swamp_location.glb')
