/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DJMaesen (https://sketchfab.com/bumstrum)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tree-a2a6237a270840e198cc7db1c47f1ef7
title: Tree
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TreeModel(props) {
  const { nodes, materials } = useGLTF('/tree.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[20.47, 228.66, -23.07]}>
            <mesh geometry={nodes.leaves_leaves_0.geometry} material={materials.leaves} />
          </group>
          <mesh geometry={nodes.tree_bark_0.geometry} material={materials.bark} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tree.glb')
